### ISSUE TITLE
Java ResourcePack: 巧克力纹理包

### ISSUE THREAD

**Issue by hbread00** [HyperCol/MGCD#15]
### 名称

巧克力纹理包

### 作者

🍞bread

### 风格

简洁

### 状态

正常更新

### 价格

免费/国服6元

### 平台

MCBBS

### 平台链接

https://www.mcbbs.net/thread-653595-1-1.html

**Comment by 17TheWord** [comment]
还是两个版都有的啊

**Comment by 17TheWord** [comment]
Auto-closing issue
