### ISSUE TITLE
Java ResourcePack: Rist_Flawless纹理

### ISSUE THREAD

**Issue by Fruge-K** [HyperCol/MGCD#24]
### 名称

Rist_Flawless纹理

### 作者

建筑师俭朴的奎

### 风格

PBR-写实

### 状态

不定时更新

### 价格

RMB5.00

### 平台

哔哩哔哩

### 平台链接

https://www.bilibili.com/video/BV1GW4y1d7LU?vd_source=d6cf51fe889d82f497fa4c4fbafca695

**Comment by 17TheWord** [comment]
Auto-closing issue
