### ISSUE TITLE
Java ResourcePack: 星落之晶

### ISSUE THREAD

**Issue by Captain5412** [HyperCol/MGCD#42]
### 名称

星落之晶

### 作者

大队长_Captain&是亚克力&小史龙吖Slime_Dragon&KuLou_D&爱玩的小尽

### 风格

晶体

### 状态

正常更新

### 价格

免费

### 平台

苦力怕论坛

### 平台链接

https://klpbbs.com/thread-101104-1-1.html

**Comment by 17TheWord** [comment]
Auto-closing issue
