### ISSUE TITLE
Java ResourcePack: Diwang Blocks系列模组材质

### ISSUE THREAD

**Issue by Fruge-K** [HyperCol/MGCD#45]
### 名称

Diwang Blocks系列模组材质

### 作者

地王之星团队：建筑师俭朴的奎

### 风格

综合

### 状态

不定时更新

### 价格

RMB 19.80

### 平台

哔哩哔哩

### 平台链接

https://www.bilibili.com/video/BV1PN411B7xj/?spm_id_from=333.999.0.0&vd_source=ec1c54f2ec5fd8ae6ba217bd46b9ce86

**Comment by 17TheWord** [comment]
Auto-closing issue
