### ISSUE TITLE
【错误反馈】（在此简单文档的错误）

### ISSUE THREAD

**Issue by wjsw3369** [HyperCol/MGCD#47]
### 模块

作品集锦->作品表格->Java版光影包

### URL

https://mgcd.hypercol.com/works/java_shaders.html

### 错误描述

itt3.0的地址错了，跳转的也是2.0的发布界面

**Comment by shaoxiu** [comment]
已修复，大佬在频道否？有一个积分奖励得在频道里给

**Comment by wjsw3369** [comment]
称不上，只是偶然碰到
我上午的时候加入了频道，积分有什么用吗
